version: '3.8'

services:
  rythme:
    build: .
    ports:
      - "8080:80"  # Map container's port 80 to localhost's port 8080
    volumes:
      - .:/usr/share/nginx/html:ro  # Mount local directory to container, read-only mode
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
